### ISSUE TITLE
Database credentials are not retrieved 

### ISSUE THREAD

**Issue by shaimaa-elsebaie** [aws/aws-secretsmanager-jdbc#233]
I am using your library with spring boot. 
```
implementation("com.amazonaws.secretsmanager:aws-secretsmanager-jdbc:2.0.2")
```

I have the following settings in my `application.yaml`:
```
spring:
  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    url: jdbc-secretsmanager:postgresql://host:5432/database_name
    user: secret_name
```

It seems that the library does not retrieve the credentials from the secret manager. When I run the spring boot application and I try to connect to the database I get the following error:
```
 Could not open JPA EntityManager for transaction] with root cause

org.postgresql.util.PSQLException: The server requested SCRAM-based authentication, but no password was provided.
```
