### ISSUE TITLE
integration with spring data

### ISSUE THREAD

**Issue by mmenard-bbc** [aws/aws-secretsmanager-jdbc#5]
I'm trying to connect to a MySQL database using AWS Secrets Manager.
My application is a Spring Boot app.

I tried to update these configs like this :

```
spring.datasource.username= arn of the secret
spring.datasource.driverClassName=com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
spring.datasource.url=jdbc-secretsmanager:mysql://...
```

But I have this error :

`No Driver has been registered with name, com.mysql.jdbc.Driver. Please check your system properties or secretsmanager.properties for typos. Also ensure that the Driver registers itself`

Previously, my config was like this :

```
spring:
  datasource:
    url: ...
    username: ...
    password: ...
    driverClassName: com.mysql.cj.jdbc.Driver
```

Thanks
